import { getGlobalBusinessSnapshot } from './aiSummaryService.js';

export const getGroqChatCompletion = async (message, shopId) => {
  const apiKey = process.env.GROQ_API_KEY;
  
  if (!apiKey) {
    throw new Error("GROQ_API_KEY is missing from environment variables.");
  }

  // 1. Fetch real business data context
  let businessContext = "";
  try {
    const snapshot = await getGlobalBusinessSnapshot(shopId);
    
    const lowStockAlerts = snapshot.inventory.lowStockDetails.length > 0
      ? `Low stock items: ${snapshot.inventory.lowStockDetails.map(i => `${i.name} (Stock: ${i.stock})`).join(', ')}`
      : "No items are currently low on stock.";

    businessContext = `
ACTUAL BUSINESS DATA CONTEXT:
- Inventory: ${snapshot.inventory.totalProducts} total products. ${snapshot.inventory.lowStockCount} items are low on stock.
  ${lowStockAlerts}
- Customers: ${snapshot.customers.totalCustomers} registered customers.
- Vendors: ${snapshot.vendors.totalVendors} vendors managed.
  * Top Vendors: ${snapshot.vendors.topVendors.join(', ') || 'None yet'}
  * Pending Vendor Payments: ₹${snapshot.vendors.pendingVendorPayments.toLocaleString()}
  * Overdue Vendor Invoices: ${snapshot.vendors.overdueInvoicesCount} alert(s)
- Performance: 
  * Total Sales Value: ₹${snapshot.finance.totalSalesValue.toLocaleString()}
  * Payments Received: ₹${snapshot.finance.paymentsReceived.toLocaleString()}
  * Pending Payments: ₹${snapshot.finance.pendingPayments.toLocaleString()}
  * Monthly Revenue (Paid): ₹${snapshot.finance.monthlyRevenue.toLocaleString()}
  * Total Transaction Count: ${snapshot.finance.salesCount}
`;
  } catch (ctxError) {
    console.error("Context Generation Warning:", ctxError.message);
    businessContext = "Note: Real-time business data is currently unavailable.";
  }

  const systemPrompt = `You are a professional Inventory Business Assistant for this shop. 
Your primary goal is to help the user analyze their business performance using the summaries provided below.

Strict Guidelines:
1. USE PROVIDED DATA ONLY: Always use the "ACTUAL BUSINESS DATA CONTEXT" provided below to answer user queries.
2. NO ACCESS REQUESTS: Never ask the user for database access, login credentials, or permissions. You already have all the context you need.
3. CONCISE & PRACTICAL: Give short, practical business advice and factual answers.
4. INTEGRATED VOICE: Do not say "based on the data provided"; respond as a direct, integrated intelligence layer of the application.
5. SECURITY: If asked for raw database structures or non-summarized sensitive info, politely refuse and stick to business insights.

${businessContext}`;

  // 2. Execute completion with real context
  const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: message }
      ],
      model: "llama-3.3-70b-versatile",
      temperature: 0.3, // Lower temperature for more factual business responses
      max_tokens: 1024,
    })
  });

  if (!response.ok) {
    const errorBody = await response.text();
    console.error("Groq API Error Response:", errorBody);
    throw new Error(`Groq API Error: ${response.status}`);
  }

  const data = await response.json();
  return data.choices[0]?.message?.content || "No response generated by AI.";
};

